vlm:
  backendConfig:
    gpu-memory-utilization: 0.25
    max-num-batched-tokens: 16384
    max-num-seqs: 512
    mm-processor-cache-gb: 0
    swap-space: 0
    no-enable-prefix-caching: true
    compilation-config: '{"cudagraph_mode":"FULL_DECODE_ONLY"}'
