apiVersion: v1
kind: Service
metadata:
  name: {{ include "paddleocr-vl-hps.name" . }}
  labels:
    {{- include "paddleocr-vl-hps.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "paddleocr-vl-hps.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
