# Use the official Golang image as the base image
FROM golang:1.22-alpine

# Set the working directory
WORKDIR /app

# Copy the Go module files
COPY fibonacci/go.mod .

# Copy the source code
COPY fibonacci/main.go .

# Build the Go application
RUN go build -o fibonacci-app main.go

# Run the application
ENTRYPOINT ["./fibonacci-app"] 