"on":
    push:
        branches:
            - dev
name: Deploy to server
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: porter apply -f porter-server-test-helm-install-latency.yaml
              env:
                PORTER_APP_NAME: server
                PORTER_CLUSTER: "2"
                PORTER_DEPLOYMENT_TARGET_ID: a683bd05-5d3a-469d-ac6b-96c3d2830bd7
                PORTER_HOST: https://yosefdev2.withporter.run
                PORTER_PROJECT: "1"
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_1_869731671 }}
