"on":
    push:
        branches:
            - main
name: Deploy to otto
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: exec porter apply
              env:
                PORTER_APP_NAME: otto
                PORTER_CLUSTER: "1"
                PORTER_DEPLOYMENT_TARGET_ID: b0d8e83e-e26c-4b88-819e-a8f263f66ae4
                PORTER_HOST: https://yosefdev2.withporter.run
                PORTER_PR_NUMBER: ${{ github.event.number }}
                PORTER_PROJECT: "1"
                PORTER_REPO_NAME: ${{ github.event.repository.name }}
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_1_1 }}
