"on":
    push:
        branches:
            - dev
name: Deploy to backend
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Override porter CLI
              run: |
                docker pull ghcr.io/porter-dev/releases/porter-cli:0.66.0-dev.1
                docker cp $(docker create --platform linux/amd64 ghcr.io/porter-dev/releases/porter-cli:0.66.0-dev.1):/usr/local/bin/porter $(which porter)
            - name: Deploy stack
              timeout-minutes: 30
              run: porter apply
              env:
                PORTER_APP_NAME: backend
                PORTER_CLUSTER: "1"
                PORTER_DEPLOYMENT_TARGET_ID: ce52561a-3361-420b-8c79-73ae1824d07c
                PORTER_HOST: https://yosefdev2.withporter.run
                PORTER_PROJECT: "1"
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_1_869731671 }}
