"on":
    push:
        branches:
            - main
name: Deploy to testserver
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: porter apply
              env:
                DOCKER_BUILDKIT: "1"
                PORTER_APP_NAME: testserver
                PORTER_CLUSTER: "1"
                PORTER_DEPLOYMENT_TARGET_ID: 7d51a723-7205-49e3-bde8-04c5753283e9
                PORTER_HOST: https://yosefdev2.withporter.run
                PORTER_PROJECT: "1"
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_1_869731671 }}
